### ISSUE TITLE
Documentation - v0.14

### ISSUE THREAD

**Issue by arthurgermano** [moleculerjs/site#85]
Hi.. last time and expressed here a minor problem in the documentation.

I found another one. 

Here it goes 
Access the link [tracing without context](https://moleculer.services/docs/0.14/tracing.html#Create-span-without-context)

Where it says
`
const span = this.broker.startSpan("initializing db", {
    tags: {
        dbHost: this.settings.dbHost
    }
});
`

Should be:
`
const span = this.broker.tracer.startSpan("initializing db", {
    tags: {
        dbHost: this.settings.dbHost
    }
});
`
Anyway just trying to help.
And I have to say.. You all have done a great job.. 
Moleculer is awesome!

Cheers!

**Comment by icebob** [comment]
Thanks @arthurgermano, 
nice catch, we will fix it!

In the future, please open document-related issues into this repo, thanks.

**Comment by AndreMaz** [comment]
Closing. Fixed in https://github.com/moleculerjs/site/commit/73973afa5dd40eb8bab1dab96f54d4904f712089. 

@arthurgermano big thanks for your help 😉 If you catch anything else you can update directly the docs. Updating is quite easy. For example: docs for https://moleculer.services/docs/0.14/tracing.html are at `source/docs/0.14/tracing.md`.
